name: release
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build in Debug
        run: dotnet build --configuration Debug --no-restore
      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: /home/runner/work/shakespeare-pokemon/shakespeare-pokemon/ShakespearePokemon.Tests/coverage.opencover.xml
      - name: Build in Release
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish --no-build --configuration Release -o publish ShakespearePokemon.API
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: shakespeare-pokemon-${{ env.VERSION }}
          path: publish    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./ShakespearePokemon.API/Dockerfile
          tags: lmazzanti/shakespeare-pokemon:latest
